# Generated by Django 4.1.5 on 2023-01-26 22:22

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('apka', '0005_alter_imagemodel_cropped_alter_imagemodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='cropped',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default.png', force_format=None, keep_meta=True, quality=-1, scale=None, size=[100, 100], upload_to='cropped'),
        ),
    ]
