# Generated by Django 4.1.5 on 2023-01-26 23:31

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('apka', '0006_alter_imagemodel_cropped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='cropped',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default.pg', force_format=None, keep_meta=True, quality=75, scale=None, size=[100, 100], upload_to='cropped'),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default.png', force_format=None, keep_meta=True, quality=75, scale=None, size=[1000, 1000], upload_to='full'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apka.imagemodel')),
            ],
        ),
    ]
