# Generated by Django 4.1.5 on 2023-01-27 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apka', '0007_alter_imagemodel_cropped_alter_imagemodel_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on']},
        ),
    ]
